# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
